# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-15 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fetched_cloud_watch_log', models.DateTimeField(blank=True, null=True)),
                ('sns_destination', models.CharField(max_length=255)),
                ('sns_dwell_time', models.PositiveIntegerField(blank=True, null=True)),
                ('sns_dwell_time_until_device_acknowledgement', models.PositiveIntegerField(blank=True, null=True)),
                ('sns_mcc', models.PositiveIntegerField(blank=True, null=True)),
                ('sns_message_id', models.CharField(max_length=255, unique=True)),
                ('sns_mnc', models.PositiveIntegerField(blank=True, null=True)),
                ('sns_phone_carrier', models.CharField(blank=True, max_length=255)),
                ('sns_price', models.FloatField(blank=True, null=True)),
                ('sns_provider_response', models.CharField(blank=True, max_length=255)),
                ('sns_sms_type', models.CharField(blank=True, max_length=255)),
                ('sns_status', models.CharField(blank=True, max_length=255)),
                ('sns_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SMS Event',
                'ordering': ['-created'],
                'verbose_name_plural': 'SMS Events',
            },
        ),
    ]
