# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-20 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_eddie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsevent',
            name='event_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
